import 'package:flutter/material.dart';
import 'package:flutterapp/smart_20parkingapp/generatedmainmenuwidget/generated/GeneratedVector1Widget.dart';

/* Frame Main menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainmenuWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 24.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedVector1Widget(),
              )
            ]),
      ),
    ));
  }
}
