import 'package:flutter/material.dart';
import 'package:flutterapp/smart_20parkingapp/generatedprofilwidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/smart_20parkingapp/generatedprofilwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/smart_20parkingapp/generatedprofilwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 120.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 120.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 24.0,
                top: 216.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 135.0,
                child: GeneratedGroup9Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06666666666666667;

                  final double height = constraints.maxHeight * 0.0375;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.0375,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup8Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
